Traceback (most recent call last):
  File "/home/murraybj/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/murraybj/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/murraybj/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/murraybj/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/murraybj/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/murraybj/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print(DWaveSamples.info)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mSolverFailureError[0m                        Traceback (most recent call last)
Cell [0;32mIn[15], line 1[0m
[0;32m----> 1[0m [38;5;28mprint[39m([43mDWaveSamples[49m[38;5;241;43m.[39;49m[43minfo[49m)

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dimod/sampleset.py:1107[0m, in [0;36mSampleSet.info[0;34m(self)[0m
[1;32m   1089[0m [38;5;129m@property[39m
[1;32m   1090[0m [38;5;28;01mdef[39;00m [38;5;21minfo[39m([38;5;28mself[39m):
[1;32m   1091[0m [38;5;250m    [39m[38;5;124;03m"""Dict of information about the :class:`SampleSet` as a whole.[39;00m
[1;32m   1092[0m 
[1;32m   1093[0m [38;5;124;03m    Examples:[39;00m
[0;32m   (...)[0m
[1;32m   1105[0m [38;5;124;03m        # Snipped above response for brevity[39;00m
[1;32m   1106[0m [38;5;124;03m    """[39;00m
[0;32m-> 1107[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mresolve[49m[43m([49m[43m)[49m
[1;32m   1108[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_info

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dimod/sampleset.py:1490[0m, in [0;36mSampleSet.resolve[0;34m(self)[0m
[1;32m   1488[0m [38;5;66;03m# if it doesn't have the attribute then it is already resolved[39;00m
[1;32m   1489[0m [38;5;28;01mif[39;00m [38;5;28mhasattr[39m([38;5;28mself[39m, [38;5;124m'[39m[38;5;124m_future[39m[38;5;124m'[39m):
[0;32m-> 1490[0m     samples [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_result_hook[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_future[49m[43m)[49m
[1;32m   1491[0m     [38;5;28mself[39m[38;5;241m.[39m[38;5;21m__init__[39m(samples[38;5;241m.[39mrecord, samples[38;5;241m.[39mvariables, samples[38;5;241m.[39minfo, samples[38;5;241m.[39mvartype)
[1;32m   1492[0m     [38;5;28;01mdel[39;00m [38;5;28mself[39m[38;5;241m.[39m_future

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dwave/system/composites/embedding.py:289[0m, in [0;36mEmbeddingComposite.sample.<locals>.async_unembed[0;34m(response)[0m
[1;32m    284[0m [38;5;28;01mdef[39;00m [38;5;21masync_unembed[39m(response):
[1;32m    285[0m     [38;5;66;03m# unembed the sampleset aysnchronously.[39;00m
[1;32m    287[0m     warninghandler[38;5;241m.[39mchain_break(response, embedding)
[0;32m--> 289[0m     sampleset [38;5;241m=[39m [43munembed_sampleset[49m[43m([49m[43mresponse[49m[43m,[49m[43m [49m[43membedding[49m[43m,[49m[43m [49m[43msource_bqm[49m[38;5;241;43m=[39;49m[43mbqm[49m[43m,[49m
[1;32m    290[0m [43m                                  [49m[43mchain_break_method[49m[38;5;241;43m=[39;49m[43mchain_break_method[49m[43m,[49m
[1;32m    291[0m [43m                                  [49m[43mchain_break_fraction[49m[38;5;241;43m=[39;49m[43mchain_break_fraction[49m[43m,[49m
[1;32m    292[0m [43m                                  [49m[43mreturn_embedding[49m[38;5;241;43m=[39;49m[43mreturn_embedding[49m[43m)[49m
[1;32m    294[0m     [38;5;28;01mif[39;00m return_embedding:
[1;32m    295[0m         sampleset[38;5;241m.[39minfo[[38;5;124m'[39m[38;5;124membedding_context[39m[38;5;124m'[39m][38;5;241m.[39mupdate(
[1;32m    296[0m             embedding_parameters[38;5;241m=[39membedding_parameters,
[1;32m    297[0m             chain_strength[38;5;241m=[39membedding[38;5;241m.[39mchain_strength)

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dwave/embedding/transforms.py:606[0m, in [0;36munembed_sampleset[0;34m(target_sampleset, embedding, source_bqm, chain_break_method, chain_break_fraction, return_embedding)[0m
[1;32m    603[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m:
[1;32m    604[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mgiven bqm does not match the embedding[39m[38;5;124m"[39m)
[0;32m--> 606[0m record [38;5;241m=[39m [43mtarget_sampleset[49m[38;5;241;43m.[39;49m[43mrecord[49m
[1;32m    608[0m unembedded, idxs [38;5;241m=[39m chain_break_method(target_sampleset, chains)
[1;32m    610[0m reserved [38;5;241m=[39m {[38;5;124m'[39m[38;5;124msample[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124menergy[39m[38;5;124m'[39m}

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dimod/sampleset.py:1126[0m, in [0;36mSampleSet.record[0;34m(self)[0m
[1;32m   1110[0m [38;5;129m@property[39m
[1;32m   1111[0m [38;5;28;01mdef[39;00m [38;5;21mrecord[39m([38;5;28mself[39m):
[1;32m   1112[0m [38;5;250m    [39m[38;5;124;03m""":obj:`numpy.recarray` containing the samples, energies, number of occurences, and other sample data.[39;00m
[1;32m   1113[0m 
[1;32m   1114[0m [38;5;124;03m    Examples:[39;00m
[0;32m   (...)[0m
[1;32m   1124[0m 
[1;32m   1125[0m [38;5;124;03m    """[39;00m
[0;32m-> 1126[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mresolve[49m[43m([49m[43m)[49m
[1;32m   1127[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_record

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dimod/sampleset.py:1490[0m, in [0;36mSampleSet.resolve[0;34m(self)[0m
[1;32m   1488[0m [38;5;66;03m# if it doesn't have the attribute then it is already resolved[39;00m
[1;32m   1489[0m [38;5;28;01mif[39;00m [38;5;28mhasattr[39m([38;5;28mself[39m, [38;5;124m'[39m[38;5;124m_future[39m[38;5;124m'[39m):
[0;32m-> 1490[0m     samples [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_result_hook[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_future[49m[43m)[49m
[1;32m   1491[0m     [38;5;28mself[39m[38;5;241m.[39m[38;5;21m__init__[39m(samples[38;5;241m.[39mrecord, samples[38;5;241m.[39mvariables, samples[38;5;241m.[39minfo, samples[38;5;241m.[39mvartype)
[1;32m   1492[0m     [38;5;28;01mdel[39;00m [38;5;28mself[39m[38;5;241m.[39m_future

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dwave/system/samplers/dwave_sampler.py:449[0m, in [0;36mDWaveSampler.sample.<locals>._hook[0;34m(computation)[0m
[1;32m    447[0m [38;5;28;01mexcept[39;00m (SolverError, InvalidAPIResponseError) [38;5;28;01mas[39;00m exc:
[1;32m    448[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39mfailover:
[0;32m--> 449[0m         [38;5;28;01mraise[39;00m exc
[1;32m    450[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(exc, SolverAuthenticationError):
[1;32m    451[0m         [38;5;28;01mraise[39;00m exc

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dwave/system/samplers/dwave_sampler.py:436[0m, in [0;36mDWaveSampler.sample.<locals>._hook[0;34m(computation)[0m
[1;32m    433[0m     [38;5;28;01mreturn[39;00m sampleset
[1;32m    435[0m [38;5;28;01mtry[39;00m:
[0;32m--> 436[0m     [38;5;28;01mreturn[39;00m [43mresolve[49m[43m([49m[43mcomputation[49m[43m)[49m
[1;32m    438[0m [38;5;28;01mexcept[39;00m (ProblemUploadError, RequestTimeout, PollingTimeout) [38;5;28;01mas[39;00m exc:
[1;32m    439[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39mfailover:

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dwave/system/samplers/dwave_sampler.py:426[0m, in [0;36mDWaveSampler.sample.<locals>._hook.<locals>.resolve[0;34m(computation)[0m
[1;32m    424[0m [38;5;28;01mdef[39;00m [38;5;21mresolve[39m(computation):
[1;32m    425[0m     sampleset [38;5;241m=[39m computation[38;5;241m.[39msampleset
[0;32m--> 426[0m     [43msampleset[49m[38;5;241;43m.[39;49m[43mresolve[49m[43m([49m[43m)[49m
[1;32m    428[0m     [38;5;28;01mif[39;00m warninghandler [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    429[0m         warninghandler[38;5;241m.[39mtoo_few_samples(sampleset)

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dimod/sampleset.py:1490[0m, in [0;36mSampleSet.resolve[0;34m(self)[0m
[1;32m   1488[0m [38;5;66;03m# if it doesn't have the attribute then it is already resolved[39;00m
[1;32m   1489[0m [38;5;28;01mif[39;00m [38;5;28mhasattr[39m([38;5;28mself[39m, [38;5;124m'[39m[38;5;124m_future[39m[38;5;124m'[39m):
[0;32m-> 1490[0m     samples [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_result_hook[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_future[49m[43m)[49m
[1;32m   1491[0m     [38;5;28mself[39m[38;5;241m.[39m[38;5;21m__init__[39m(samples[38;5;241m.[39mrecord, samples[38;5;241m.[39mvariables, samples[38;5;241m.[39minfo, samples[38;5;241m.[39mvartype)
[1;32m   1492[0m     [38;5;28;01mdel[39;00m [38;5;28mself[39m[38;5;241m.[39m_future

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dwave/cloud/computation.py:833[0m, in [0;36mFuture.sampleset.<locals>.<lambda>[0;34m(f)[0m
[1;32m    830[0m [38;5;28;01mif[39;00m sampleset [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    831[0m     [38;5;28;01mreturn[39;00m sampleset
[0;32m--> 833[0m sampleset [38;5;241m=[39m dimod[38;5;241m.[39mSampleSet[38;5;241m.[39mfrom_future([38;5;28mself[39m, [38;5;28;01mlambda[39;00m f: [43mf[49m[38;5;241;43m.[39;49m[43mwait_sampleset[49m[43m([49m[43m)[49m)
[1;32m    835[0m [38;5;66;03m# propagate id to sampleset as well[39;00m
[1;32m    836[0m [38;5;66;03m# note: this requires dimod>=0.8.21 (before that version SampleSet[39;00m
[1;32m    837[0m [38;5;66;03m# had slots set which prevented dynamic addition of attributes).[39;00m
[1;32m    838[0m sampleset[38;5;241m.[39mwait_id [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mwait_id

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dwave/cloud/computation.py:771[0m, in [0;36mFuture.wait_sampleset[0;34m(self)[0m
[1;32m    768[0m [38;5;250m[39m[38;5;124;03m"""Blocking sampleset getter."""[39;00m
[1;32m    770[0m [38;5;66;03m# resolve response[39;00m
[0;32m--> 771[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_load_result[49m[43m([49m[43m)[49m
[1;32m    773[0m [38;5;66;03m# check if sampleset already resolved (e.g. returned in response)[39;00m
[1;32m    774[0m sampleset [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_sampleset() [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_sampleset [38;5;28;01melse[39;00m [38;5;28;01mNone[39;00m

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dwave/cloud/computation.py:907[0m, in [0;36mFuture._load_result[0;34m(self)[0m
[1;32m    905[0m [38;5;66;03m# Check for other error conditions[39;00m
[1;32m    906[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_exception [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 907[0m     [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39m_exception
[1;32m    909[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39m_result_write_lock:
[1;32m    910[0m     [38;5;66;03m# If someone else took care of decoding while we were waiting[39;00m
[1;32m    911[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m~/CHE498/QUBOBook/.venv/lib/python3.10/site-packages/dwave/cloud/client/base.py:1341[0m, in [0;36mClient._handle_problem_status[0;34m(self, message, future)[0m
[1;32m   1339[0m [38;5;28;01mif[39;00m [38;5;124m'[39m[38;5;124merror_code[39m[38;5;124m'[39m [38;5;129;01min[39;00m message [38;5;129;01mand[39;00m [38;5;124m'[39m[38;5;124merror_msg[39m[38;5;124m'[39m [38;5;129;01min[39;00m message:
[1;32m   1340[0m     logger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mError response received: [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m, message)
[0;32m-> 1341[0m     [38;5;28;01mraise[39;00m SolverFailureError(message[[38;5;124m'[39m[38;5;124merror_msg[39m[38;5;124m'[39m])
[1;32m   1343[0m [38;5;28;01mif[39;00m [38;5;124m'[39m[38;5;124mstatus[39m[38;5;124m'[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m message:
[1;32m   1344[0m     [38;5;28;01mraise[39;00m InvalidAPIResponseError([38;5;124m"[39m[38;5;124m'[39m[38;5;124mstatus[39m[38;5;124m'[39m[38;5;124m missing in problem description response[39m[38;5;124m"[39m)

[0;31mSolverFailureError[0m: Problem not accepted because user has insufficient remaining solver access time in project DEV.

